name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.x

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x


      - name: install dep
        run: pnpm i

      - name: run test
        run: pnpm test
